version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: &env_file
      - .env.dev
    volumes:
      - .:/app
      - ./dev/data/history:/history
      - /app/node_modules/
    depends_on:
      - db
    ports:
      - 6001:3000

  db:
    image: postgres
    volumes:
      - ./dev/data/db:/var/lib/postgresql/data
    env_file: *env_file

  pgadmin:
    image: dpage/pgadmin4:4.18
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost.dev
      PGADMIN_DEFAULT_PASSWORD: '00000000'
      PGADMIN_LISTEN_PORT: 80
    ports:
      - '6080:80'
    volumes:
      - ./dev/data/pgadmin:/var/lib/pgadmin
    depends_on:
      - db
